### ISSUE TITLE
Bulk endpoint /universe/types/

### ISSUE THREAD

**Issue by Ionaru** [esi/esi-issues#1001]
# Feature Request

Bulk types endpoint that returns an array of type data objects, like `/universe/names`.

## Use case

Displaying info for multiple items at once, or doing a specific check (on the `published` attribute for example) on multiple items.

This to avoid multiple calls to `/universe/types/{type_id}`

## Authentication

Public route, no auth required.

### Request
A POST request with item IDs array in the body.

```
POST /universe/types/
[34, 35]
```

### Return
```json
[
  {
    "capacity": 0,
    "description": "...",
    "group_id": 18,
    "icon_id": 22,
    "market_group_id": 1857,
    "mass": 0,
    "name": "Tritanium",
    "packaged_volume": 0.01,
    "portion_size": 1,
    "published": true,
    "radius": 1,
    "type_id": 34,
    "volume": 0.01
  },
  {
    "capacity": 0,
    "description": "...",
    "group_id": 18,
    "icon_id": 400,
    "market_group_id": 1857,
    "mass": 0,
    "name": "Pyerite",
    "packaged_volume": 0.01,
    "portion_size": 1,
    "published": true,
    "radius": 1,
    "type_id": 35,
    "volume": 0.01
  }
]
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [x] Feature does not require auth
- [ ] Meta feature, applies to all routes

Related to #633

**Comment by tsuthers-ccpgames** [comment]
/universe/names/ already accepts typeids to resolve names:

curl -X POST "https://esi.evetech.net/latest/universe/names/?datasource=tranquility" -H  "accept: application/json" -H  "Content-Type: application/json" -d "[ 487,  644]"

We don't create multi-request endpoints for querying the details of things because it lowers the cache hit rate since almost every query would contain a unique mix of items. We need to keep the cache hit rate high and the cache cost cheap to support not having rate limits.
