### ISSUE TITLE
/characters/{character_id}/mining/ sorting

### ISSUE THREAD

**Issue by andrey-maklakov** [esi/esi-issues#1007]
# Bug

Wrong results sorting for character's mining journal. 
Please change results ordering to descending as shown in example on the site.
https://esi.evetech.net/latest/#!/Industry/get_characters_character_id_mining

## Request

`GET /characters/{character_id}/mining/?datasource=tranquility`

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

{
  "application/json": [
    {
      "date": "2017-09-18",
      "quantity": 5199,
      "solar_system_id": 30003707,
      "type_id": 17471
    },
    {
      "date": "2017-09-19",
      "quantity": 7004,
      "solar_system_id": 30003707,
      "type_id": 17471
    }
  ]
}

## Expected

{
  "application/json": [
    {
      "date": "2017-09-19",
      "quantity": 7004,
      "solar_system_id": 30003707,
      "type_id": 17471
    },
    {
      "date": "2017-09-18",
      "quantity": 5199,
      "solar_system_id": 30003707,
      "type_id": 17471
    }
  ]
}

# Checklist

Check all boxes that apply to this issue:

- [ ] Bug description is provided
- [ ] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by ddavaham** [comment]
This is not a bug. Nothing in the spec states that this endpoint is sorted at all. Just because the example has two entries and the one below the first has a date preceding the one above it does not indicate that the endpoint is sorted/ordered in chronological order.

This however did raise a separate issue that we noticed in tweetfleet. We noticed that no where throughout the spec other than the description of an endpoint is it mentioned that an endpoint is sorted, if sorting of the returned data is even supported. I am going to leave this issue open, but it is a feature request at best, not a bug. A separate feature request will be opened to discuss how an attribute of sorts can be inserted to indicate that the endpoint is sorted and/or how it is sorted, if this is even needed.

**Comment by tsuthers-ccpgames** [comment]
As a general rule, we don't guarantee ordering. Swagger specs don't provide any way to enforce it or specify to clients that they should expect it, and it's also extra processing work on the server side that's just not that hard for clients to do but in aggregate adds noticeable load on the server on at least some endpoints. For these reasons we have made a deliberate choice to not make some kind of soft promise about ordering that we can't follow through on.

Most of the endpoint examples are in order because they were written by humans, and quite a lot of endpoints return their data in an ordered fashion because that's how it gets stored internally in the monolith, but with the possible exception of some of the oldest endpoints which still use the weird "last_whatever_id" paginating we return the data in whatever order it was retrieved from the origin datasource, which strictly speaking means that the order could be anything.

**Comment by andrey-maklakov** [comment]
@ddavaham @tsuthers-ccpgames 
But this request has a pagination... and I must to check next pages for latest records receiving. Looks little bit strange.

**Comment by tsuthers-ccpgames** [comment]
This endpoint uses new-style (sane) pagination. It returns an X-Pages header on every request telling you how many total pages there are for that route. You should request the first page, check the X-Pages header, and if it's greater than 1, fetch every other page concurrently and merge and sort the result.

You can read more here: https://developers.eveonline.com/blog/article/esi-concurrent-programming-and-pagination

**Comment by andrey-maklakov** [comment]
@tsuthers-ccpgames 
Thank you again :)
