### ISSUE TITLE
Unhandled internal error while requesting contacts for specific character.

### ISSUE THREAD

**Issue by mattftw** [esi/esi-issues#1020]
# Bug

When requesting a list of contacts for a specific user of my application, the server responds with a 500 / unhandled internal error. There seems to be something broken about one character in particular.

## Request
`GET https://esi.evetech.net/v2/characters/{character_id}/contacts/?page=1`
I'd rather not post the characters ID publicly as i don't want to involve the end-user.
Presumably a developer can retrieve the missing information from the request ID below? Alternatively please feel free to send me a message.

## Response
```json
{"error":"Unhandled internal error encountered!"}
```

### Status Code
`500`

### Headers
```Date: Mon, 27 Aug 2018 14:27:47 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 49
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,If-None-Match,X-User-Agent
Access-Control-Allow-Methods: DELETE,GET,POST,PUT,HEAD,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
Access-Control-Max-Age: 600
Allow: DELETE,GET,HEAD,OPTIONS,POST,PUT
Strict-Transport-Security: max-age=31536000
X-Esi-Error-Limit-Remain: 98
X-Esi-Error-Limit-Reset: 13
X-Esi-Request-Id: d922c11f-ae03-4966-979d-13df3ab5a1ec
```

### Body
```json
{"error":"Unhandled internal error encountered!"}
```

## Expected
The standard list of contacts

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [ ] Expected response is provided

**Comment by a-tal** [comment]
from looking into this quickly, it seems that this character has an NPC character added as a contact, and that NPC character doesn't exist anymore.

when looking up the affected character's contacts in ESP I get a 500 there as well, with `KeyError: ('Not an owner', <npc_character_id>)`

will need a monolith fix to resolve. in the meantime, you could try having them look through their contacts list for some weirdo non-existent character and delete them. if you want to ping me on slack with the character ID I can send you the contact ID if you prefer to delete the contact via ESI instead of in-client.

**Comment by tsuthers-ccpgames** [comment]
Hrm, NPC characters probably shouldn't be getting deleted in the first place. What's the current status of this ticket? Is this still an issue, or has it been resolved?

**Comment by tsuthers-ccpgames** [comment]
Closing due to lack of response.
