### ISSUE TITLE
Feature request for /characters/{character_id}/planets/{planet_id}/

### ISSUE THREAD

**Issue by Grasume** [esi/esi-issues#1034]
Currently their is no way to know besides in game if a Launch pad is empty or Full or even Half . Requesting something be added as below example in response. Currently response for lanuchpad is as follows if you drill down .   {'latitude': 1.45420680101, 'longitude': 1.56851994631, 'pin_id': 1026425145466, 'type_id': 2544}

get_characters_character_id_planets_planet_id_ok{
     get_characters_character_id_planets_planet_id_pins[
         get_characters_character_id_planets_planet_id_Launch_pad{
            amount : 1000 (example)
  }
 }
}

**Comment by cvweiss** [comment]
Since you have to log in anyway to have your PP information upgraded, doesn't that defeat the purpose of this suggested endpoint?

Also, you completely skirted the Feature Request template, tsk tsk

**Comment by Grasume** [comment]
First not really I have several planets where I input material into 2 Launchpads and get the out put sent to Third Launchpad. It would be good to know when i need to go and fill up the Input Launch pads.

No i didn't skirt the FR template it wasn't a template more like what to put as Ive put all that.

**Comment by Aidansavage** [comment]
It's called a template because it provides a standard layout that's easy to read (and because they usually _close_ new issues not following templates). Additionally, ESI more than likely provides _precisely what you're asking for already_ given that the Neocom II app tells you just that:
![image from ios](https://user-images.githubusercontent.com/2295059/45400521-7ef21780-b61a-11e8-8a70-40aa617decde.png)
 You'll have to ask the guy who made it how he figured it out, because I'm not sure >_>

**Comment by ccp-zoetrope** [comment]
Closing this as it did not use the template as pointed out by @cvweiss. The template is there to help make it more readable and we have a policy to close new issues not using a template. If you haven't been able to figure out how to get this info like Neocom does then feel free to open another issue using the template 😄. Feel free to jump on the [tweetfleet slack](https://www.fuzzwork.co.uk/tweetfleet-slack-invites/) #esi channel and ask around there to see if someone knows how to get this info already.
