### ISSUE TITLE
[esi-mail] is_read property is not returned on unread mails

### ISSUE THREAD

**Issue by RMo-Sloth** [esi/esi-issues#1037]
# Bug: is_read property is not returned on unread mails

When requesting mail headers the is_read property is not returned when it should be false.

## Request

`GET latest/characters/{character_id}/mail/`

### Status Code

`200`

### Body

`[{"from":2114453994,"labels":[1],"mail_id":372483128,"recipients":[{"recipient_id":95958477,"recipient_type":"character"}],"subject":"Hey","timestamp":"2018-08-28T04:24:00Z"},
{"from":93145209,"is_read":true,"labels":[1],"mail_id":355440080,"recipients":[{"recipient_id":95958477,"recipient_type":"character"}],"subject":"FW: First mining op","timestamp":"2015-11-10T23:41:00Z"}]`

( Notice that the first request has no is_read property )

## Expected

`[{"from":2114453994,"is_read":false,"labels":[1],"mail_id":372483128,"recipients":[{"recipient_id":95958477,"recipient_type":"character"}],"subject":"Hey","timestamp":"2018-08-28T04:24:00Z"},
{"from":93145209,"is_read":true,"labels":[1],"mail_id":355440080,"recipients":[{"recipient_id":95958477,"recipient_type":"character"}],"subject":"FW: First mining op","timestamp":"2015-11-10T23:41:00Z"}]`

**Comment by antihax** [comment]
If it is not there, it is not read. This is default behavior.

Please also use the template when filing bugs.

**Comment by RMo-Sloth** [comment]
What is the reasoning here? The ESI-spec states that it should return a boolean value: [https://esi.evetech.net/dev/#!/Mail/get_characters_character_id_mail](https://esi.evetech.net/dev/#!/Mail/get_characters_character_id_mail).

Won't it be much easier for developers if it returned a boolean value? 

- There would be no risk of an unexpected 'undefined'  creeping into applications.
- Developers won't have to check if a the 'isRead'-property exists and assign a value based on that. They could just assign the expected boolean value.

**Comment by ddavaham** [comment]
The reason here is that this is the default behavior for ESI. If the property is not required, then it is not returned if its purpose is not served. The purpose of the `is_read` property is to tell if the mail is read. Instead of looking at the value of the property, just look for the property. It is safe to assume that if the property is present in the response, the mail is read, if not, then it isn't. Easy Peasy.

**Comment by alexbaileyuk** [comment]
I've got to say I really disagree with the ESI design in cases like this.

If something is a boolean, it should return false or true. Otherwise, it's description should be true or undefined. In some languages undefined will equate to false and in some languages something like 'if (mail. is_read)' would work fine with the ESI spec but in others that are more strict for types undefined this will throw an error especially if you are creating an object with them.

For the sake of 20 odd bytes, just return false. Yes this overhead will increase a little with scale but working for a company who serves a similar level of traffic from an api, this isn't what we would call the right implementation.

**Comment by SpeedProg** [comment]
the boolean attribute is marked as optional through, so it actually is defined as true, false and not there in the spec :P and from the linked article you can see that the none existance in the case of booleans and ESI means that either the attribute is false.

**Comment by alexbaileyuk** [comment]
Yet that documentation is incorrect in a way since it is never false?

It's no big deal but it clearly causes some confusion.

**Comment by Aidansavage** [comment]
The documentation is correct. When the default value of that attribute is false, and the attribute is _optional_, then when the actual value equates the default value, _of course_ it's likely to be omitted, based on the spec ESI is following.  It's a similar situation to `/characters/{character_id}/industry/jobs/`. The parameter `include_completed` is a Boolean as well, but the default behavior of omitting the parameter is the implication that it's _false_. It only becomes relevant when you want it to be a `true` value instead. That's likely how it's being treated with regards to mails.

https://www.fuzzwork.co.uk/tweetfleet-slack-invites/ & #esi to more easily discuss.
