### ISSUE TITLE
500 on wallet journal

### ISSUE THREAD

**Issue by mattftw** [esi/esi-issues#1063]
# Bug

When requesting wallet journal, a 500 error occurs for some users of my application.
Request ID is: `09ada0a7-f0ab-4365-8f33-ee281c298ae8`

## Request

`GET https://esi.evetech.net/latest/characters/...../wallet/journal/?datasource=tranquility&page=1&token=......`

## Response
```json
{
  "error": "Unhandled internal error encountered!"
}
```

### Status Code

`500`

### Headers
```access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: GET,HEAD,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: GET,HEAD,OPTIONS 
 content-length: 49 
 content-type: application/json; charset=UTF-8 
 date: Mon, 19 Nov 2018 06:45:10 GMT 
 status: 500 
 strict-transport-security: max-age=31536000 
 x-esi-error-limit-remain: 99 
 x-esi-error-limit-reset: 50 
 x-esi-request-id: 09ada0a7-f0ab-4365-8f33-ee281c298ae8
```

### Body
```json
{
  "error": "Unhandled internal error encountered!"
}
```

## Expected

200, list of journal entries

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by jennej** [comment]
I've been getting this too.

**Comment by ccp-zoetrope** [comment]
This is happening because of a new wallet journal type called "structure_gate_jump". If you have payed for the use of an Ansiblex Jump Gate then you will hit this error on this route. There is a v5 of this route that will include this new journal type ([seen here in eve-glue](https://github.com/esi/eve-glue/blob/master/eve_glue/wallet_journal_ref.py#L129)) but unfortunately there is also a fix in the monolith that needs to be deployed first. That fix is in staging and should be coming out this week. When it does I'll launch v5/characters/{character_id}/wallet/journal and update this issue.

**Comment by ccp-zoetrope** [comment]
The monolith fix was deployed during downtime today and [/v5/characters/{character_id}/wallet/journal/](https://esi.evetech.net/ui/?version=dev#/Wallet/get_characters_character_id_wallet_journal) has been released. You will need to move to using that route to get info on "structure_gate_jump" wallet transactions.
