### ISSUE TITLE
Get only specific orders with type_id from citadels

### ISSUE THREAD

**Issue by Zyles** [esi/esi-issues#1145]
# Feature Request

Is this really not supported?

Get orders for specific type_id in `/markets/structures/{structure_id}/`

P.S. You drove away Evernus developer with this feature and he stopped updating his software. I guess he had enough (like me soon).

https://www.reddit.com/r/Eve/comments/8hujh2/market_data_and_esi_a_short_story/

Well played.

## Use case

Get the orders only for a specific type_id instead of having to paginate through hundreds of pages (INSANE).

## Authentication

Yes

**Comment by lukasni** [comment]
This has been brought up in the past and it's been said that it won't be added since it both messes with the way ESI caches things and adds unnecessary load to the ESI servers. Pull all pages for the citadel and filter out accordingly, make sure to leverage local caching utilities and not fetch more than necessary.

Working with ESI requires a different approach than the old XML API did. You will have to leverage concurrent requests to work with it efficiently. See my comment in #1146 if you want to join us on tweetfleet to see what some approaches are that other people are using to work with the changed requirements in ESI.
