### ISSUE TITLE
Request: Reduce /characters/{character_id}/ cache time back to 1 hour

### ISSUE THREAD

**Issue by paulipa** [esi/esi-issues#1155]
The cache time for this endpoint seems to be increased to 24 hours. 

As a lot of corporations that are player run use systems to check if a character is part of those corporations via this endpoint before they let them access their comms, web services etc. this now causes a day of wait for new players joining the corporation before they can access anything.

I run a massive easy entry corporation that heavily focuses on recruiting new players. Now that we have to wait 24 hours before we can get them on proper comms (discord in this case) and i feel its just a waste, unless there is a very heavy reason to keep this cache as high as 24 hours.

**Comment by lukasni** [comment]
The cache timer had to be changed because of misuse that caused slowdowns in the monolith impacting the game.

For your use case, there is [`POST /characters/affiliation/`](https://esi.evetech.net/ui/#/Character/post_characters_affiliation) which is on a 1h cache timer and can be used for single characters or bulk and gives you the corporation, alliance and faction.

**Comment by lukasni** [comment]
I've opened #1156 for a possible reduction of the cache timer on `/characters/affiliation/`
