### ISSUE TITLE
Character API no longer present

### ISSUE THREAD

**Issue by ianlewis** [esi/esi-issues#1308]
It seems that somehow the character API has been completely removed and no longer shows up on the [swagger interface](https://esi.evetech.net/ui/#/). All character API endpoints seem to be returning 404.

**Comment by Blacksmoke16** [comment]
![image](https://user-images.githubusercontent.com/12136995/148312940-28c4e1f5-4fa6-420a-a1f8-0039a297452e.png)

Somewhat of a known issue. Consider this a test of your apps error handling :S.

**Comment by ianlewis** [comment]
I'll definitely use the opportunity to make improvements but it's kind of an important endpoint as it's the only way IIUC to check if a character actually exists.

**Comment by Eingang** [comment]
Not true. You can do a lookup by character name using the `/universe/ids/` endpoint. That is *still* working… sometimes. I'm seeing a lot of 504 gateway errors (even going via esi.evetech.net) but it otherwise works and is still showing in the Swagger interface.  If you give it a pile of character names, today it's returning a response with the ones it could resolve or an empty set if it couldn't resolve any names. 

BTW: You could also normally use `/characters/affiliation/` except the entire `/character/` set is gone currently. That's also a bulk endpoint. And it borks if a name in the set doesn't exist unlike the universe one.

**Comment by Blacksmoke16** [comment]
This is resolved according to slack.
