### ISSUE TITLE
500 Error in corporate assets "Invalid 200 response: 'location_type' is required, 'location_flag' is required"

### ISSUE THREAD

**Issue by pvyParts** [esi/esi-issues#1352]
# Bug
ESI intermitently returns an error when requesting corporate assets

```
Invalid 200 response: 'location_type' is required, 'location_flag' is required
```

## Request

```
curl -X GET "https://esi.evetech.net/latest/corporations/98602306/assets/?datasource=tranquility&page=1&token=123abc" -H "accept: application/json" -H "Cache-Control: no-cache"
```
### Status Code

`500`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
 date: Sun, 18 Jun 2023 07:51:46 GMT 
 x-esi-request-id: 8d4b9040-0494-4a34-9c38-d88da791cbbf 
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
  "error": "Invalid 200 response: 'location_type' is required, 'location_flag' is required",
  "response": [
    {
      "is_blueprint_copy":false,
      "type_id":2048,
      "is_singleton":false,
      "item_id":1041817873460,
      "location_id":1036957801720,
      "quantity":1
    }
    999 other items that are valid
  ],
  "sentry_id": "065617b2f43e4f72b7cca998b1f8700e"
}
```

That location ID is an office folder in a keepstar in nullsec. more details can be given if needed. 

## Expected

Please provide either the expected return code, correct response body, header value, or some combination thereof. E.g.:

`200` and a list of items as per the spec

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by MrRuthMN** [comment]
Appears to be due to the new corporation project hangar added in the Viridian expansion.  Items from contributing to a corp project stored in this hangar don't have a location_flag value passed, causing the request to error.  Removing all items from the project hangar and waiting for the endpoint cache to refresh resolved the issue for us.  

See the following example.  The first item is in corp deliveries and has a location_flag value.  2nd item was in the new project hangar, missing the location_flag value.
![ESI Example](https://github.com/esi/esi-issues/assets/59377595/68da6fb9-69ed-4450-a2b8-75c294fab853)

**Comment by soratidus999** [comment]
CorporationGoalDeliveries should have been added last year https://github.com/esi/eve-glue/commit/1824792d04c14f6bf4e5839735d812b6e6b33231

Can you confirm?

**Comment by pvyParts** [comment]
I haven't seen this in a very long time so assume fixed yes.
