### ISSUE TITLE
403 Response when all Scopes are granted in auth_token

### ISSUE THREAD

**Issue by turulix** [esi/esi-issues#1397]
# Bug

403 Response on any authenticated (only tested on characters/blueprints) when all scopes available are selected and requested within the access_token

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET /v3/characters/{character_id}/blueprints/`

### Status Code

`403`

### Headers

![image](https://github.com/user-attachments/assets/09936e66-c31f-4f42-a196-f4330448e806)

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
    "error": "authentication failure"
}
```

## Expected
`200`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Dusty-Meg** [comment]
Has been an issue since the day the new SSO was released.
Also wrong repository for this issue, its not a ESI issue but a SSO issue.

https://github.com/ccpgames/sso-issues

**Comment by soratidus999** [comment]
If you are requesting every scope, you are ignoring best practice and requesting scopes you have no use for. This is because some of the active scopes have no actual use in ESI currently.

Please utlize esi respectfully and only request the scopes you actually need, preferably on demand

This is a known issue and documented in https://github.com/esi/esi-issues/issues/1089
