### ISSUE TITLE
Public Contract endpoint

### ISSUE THREAD

**Issue by fuzzysteve** [esi/esi-issues#61]
Contract endpoint, displaying all contracts, of all types, which are public

Possibly with some kind of limiter. pagination will be a must. 

I'm thinking a list view (ids only), and then a individual details view

**Comment by wtfrank** [comment]
This would be great because I can imagine third parties implementing all kinds of augmented search functionality that are not available in game.

1) courier contracts: ability to filter out highsec islands, or search by reward / jump (instead of just reward)

2) item contracts: a more "market-like" interface to searching for researched bps and other items

**Comment by NathenSample** [comment]
Limiter - Certainly.
Pagination - Certainly.
Response with the ID - Yep.

However could we add to that so the response also includes the ESI url to call to get the details i.e

`{
   id:123
   esiUrl:"Mock":
}`

**Comment by fuzzysteve** [comment]
ideal world, as I see it:

You can get a list of all contracts that you can see.

You can get a list of personal/corp/alliance only contracts (filter parameter?)

**Comment by Ligraph** [comment]
I assume you mean contracts made to you, your corp, or your alliance?  That would be extremely nice.

**Comment by fuzzysteve** [comment]
My preference is also to have public contracts on the endpoint.

So you can restrict to you, yourself, your alliance, or get _everything_

**Comment by Ligraph** [comment]
Yeah, I meant to include that...

**Comment by aydjay** [comment]
+1 I would like to query the ships that are stocked in my alliance staging citadel.

I don't see this as needing a director level api - any toon in the alliance should be able to query this just as we can ingame.

**Comment by markus-lassfolk** [comment]
Agreed.  And be able to search for public contracts containing BPCPacks and include that in manufacturing costs.

**Comment by Zyles** [comment]
At least let us get contracts on our character/corp.

**Comment by ETristram** [comment]
Character and corporate contracts are now available via ESI, however currently no endpoint for "general" public contracts. 

Any news on this? 
Is there a game design decision open?

**Comment by ccp-zoetrope** [comment]
Sending this through the game design ringer.

**Comment by ccp-zoetrope** [comment]
Approved by game design.

**Comment by deadlybulb** [comment]
Awesome sauce.  Best news of the day (so far).

**Comment by fuzzysteve** [comment]
hmm. you _might_ want to have a little more information on the initial listing than just the ID. like the type, or maybe the region. Or the end date. It's not vital, but it's potentially of use. Might cut down on how much people request.

**Comment by Aidansavage** [comment]
Depending on how you can access the contract stuff through ESI, and how the cache behavior would end up being, it would be great to have more control over filtering through the api.

- All/specific Region (ingame only restricts acceptance to current region for pub contracts)
- Contract type, whether it's WTB, WTS or an auction
- ItemType, including exact match (ie strict), and potentially the `exclude multiple` filter option as well

`https://esi.tech.ccp.is/latest/contracts/public/{region}/?datasource=tranquility&contract_type=auction&item_type=1,2,3,etc`
^Potential example?

**Comment by BTFO** [comment]
If this becomes a thing, could we please get a endpoint that allows us to open the contract in the game client?

**Comment by Dusty-Meg** [comment]
That is already in https://esi.tech.ccp.is/ui/#/User_Interface/post_ui_openwindow_contract

**Comment by BTFO** [comment]
Seems i missed that one, thanks 👍

**Comment by querns** [comment]
Another thing that would be handy to have, with the advent of the Abyssal modules and their unique item information, is the ability for a structure owner to dump all contracts currently posted in a structure. Something like:

`https://esi.tech.ccp.is/latest/structures/{structureID}/contracts/?datasource=tranquility&page=1`

The intended purpose of this would be to allow a structure owner to collect and disseminate a list of available Abyssal modules (and other things, like rigged ships) via a third-party site. This is essential for smooth trade of Abyssal modules, since their randomly-augmented item attributes will, in all likelihood, require trade via the contracts system.

The endpoint would need to be limited in scope, of course -- private contracts would be mostly noise. Perhaps public, alliance- and corporation-scoped contracts?

**Comment by OrthoLoess** [comment]
I agree with Steve that a little more info on the main list of IDs would help avoid a hell of a lot of unnecessary requests. Simple things like the type of contract, maybe location or region. whatever isn't too costly to build up I suppose.

**Comment by NathenSample** [comment]
Contract Type
Region ID (I feel like specific location is likely overkill, but may not be much more overhead to build in)
Would all be incredibly useful stats to avoid needlessly sifting through a multiple calls only to realise you have zero interest in the contract. 

My initial thoughts also included
Time Created
Expiry Time
But quickly realised they were actually of no help to a use case I could think of.

**Comment by sei15** [comment]
Any updates on this?

**Comment by graywolf** [comment]
Any update on this? I would like to build custom contract search tool for myself but without way to list all contracts it's not possible `.·´¯`(>▂<)´¯`·.`

**Comment by a-tal** [comment]
released under `/contracts/public/...`

**Comment by ddavaham** [comment]
Nto cool bro. 

First off, this request was made right after ESI was announced. Idea were flooding in and this one stuck. However, the priority from the get go was parity with Crest and Xml. This was just achieve earlier this year. 

Secondly, this is functionality that literally has no reference point. Meaning they had to design these endpoints from the ground up, unlike a majority of the parity work where they had something to work on

In reality, it really only took 3 months of work. Loose guesstimation. Maybe but def not two years.  So step back a little bit, be glad that you have it and say thank you instead of being an asshole.

**Comment by evrial** [comment]
I totally didn't want to trigger someone but it's all good. As long as progress moving forward is alright, we aren't customers here in the end.
