### ISSUE TITLE
Endpoint Addition: GET /characters/{character_id}/fleet/ * Display character_id of fleet Boss

### ISSUE THREAD

**Issue by testfax** [esi/esi-issues#613]
Please incorporate the boss character ID into /characters/{character_id}/fleet/

Would be superhelpful in not having to iterate through a list of character ID's previously saved until a "new" boss is found within the same fleet of character_ids. I'm currently iterating through it that way.

**Comment by DaneelTrevize** [comment]
I'd instead propose this attribute be listed under GET /fleets/{fleet_id}/

The existing "role:" under /characters/{character_id}/fleet/ can indicate if the specific character has "...(Boss)" or not. But it also gives the Fleet ID, and this is how the other details of the fleet and its other members should be found (outside of GET /fleets/{fleet_id}/members/), rather than under /characters/...

**Comment by testfax** [comment]
You should be able to see who is boss of a fleet from any character. That's the end result i'm looking for.

**Comment by lukasni** [comment]
This was added in v2 of the endpoint
