### ISSUE TITLE
Corporation Asset Locations/Names `item_ids` Guidance

### ISSUE THREAD

**Issue by leonjza** [esi/esi-issues#718]
# Inconsistency
Currently, the `/corporations/{corporation_id}/assets/locations/` and `/corporations/{corporation_id}/assets/names/` accept a body of `item_ids` for location and name lookups. However, when invalid ID's are provided the endpoint responds with an HTTP 404 and a body message of `{"error":"Invalid IDs in the request"}`.

What are the 'rules' around acceptable `item_ids` for these endpoints? I am currently providing ids sourced from the `/corporations/{corporation_id}/assets/` endpoint, however most of them cause this 404 response. If I use the `location_id` from the assets listing endpoint, less 404 responses are returned, but I am not sure if the data is correct.

fwiw: The corresponding character endpoints does not have this behaviour.

### Routes
`/corporations/{corporation_id}/assets/locations/`
`/corporations/{corporation_id}/assets/names/`

### Description
It is not clear which ids are to be provided for corporation location / name lookups.

### Resolution
Provide clarity around which ids are not considered invalid, be it `type_id`'s in a certain group or something else.

**Comment by warlof** [comment]
Bump

**Comment by tsuthers-ccpgames** [comment]
ESI-issues tickets aren't really a great place to ask questions because they get used more like a to-do list. As you see, they can go without attention for a while as they percolate up the stack.

This is a question that would be better answered by hopping on the #esi channel in the [tweetfleet slack](https://tweetfleet.slack.com/) ([invite here](https://www.fuzzwork.co.uk/tweetfleet-slack-invites/)) and asking people how they've solved this problem in the past. If it turns out there's a bug in the endpoint or the endpoint documentation could be more specific, a new and more targeted ticket should be opened that contains a clearly defined task.

Usually I'd give the answer here anyway but I don't know it off the top of my head, and I'm pretty sure that someone in #esi will. I'm going to close this ticket, hope to see you in slack :)

**Comment by leonjza** [comment]
@tsuthers-ccpgames Thanks for the response. Any hints on how I can reword a new ticket to ask which type ids are considered valid as a documentation enhancement? That is really what this ticket is asking.
