### ISSUE TITLE
esi/wallet/* documentation

### ISSUE THREAD

**Issue by jlyon87** [esi/esi-issues#731]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Inconsistency

### Routes
`/wallet/journal`
`/wallet/transactions`

### Description
More documentation details around the behavior of these endpoints is desired. How far back do they retrieve history? Do they behave differently for Alpha/Omega?

### Resolution
Add documentation to the EVE Swagger Interface for clarification.

**Comment by Seavert** [comment]
@Aidansavage what an irresponsible answer :)
![wallet_journal](https://user-images.githubusercontent.com/33360486/35410091-41635d92-0225-11e8-95ec-b49b5613b3bb.png)

**Comment by jlyon87** [comment]
now i dont know what to believe.

**Comment by CarbonAlabel** [comment]
For reference, 90 days of history are available in-game, while the API only does 30 days. It has been this way since the XML API, and ESI has inherited this limit. 

The documentation on the wallet journal endpoints now includes that notice, but it's still missing on the wallet transaction endpoints and should be added to those as well.

**Comment by Xamber** [comment]
It will be shipped with "v2" versions of the transaction endpoints.
