### ISSUE TITLE
Return Fleet Boss character_id with character/{character_id}/fleet endpoint

### ISSUE THREAD

**Issue by Flupster** [esi/esi-issues#774]
# Feature request
Return the fleet boss character_id with the /characters/{character_id}/fleet/ endpoint

### Route
/characters/{character_id}/fleet/

### Use case
you can use this information to pull the full fleet information if we have a token for the fleet boss

### Example returns
```
{
  "fleet_id": 1234567890,
  "wing_id": -1,
  "squad_id": -1,
  "role": "fleet_commander",
  "fleet_boss_character_id": 123456789
}
```

Alternatively a fleet finder endpoint?

**Comment by DaneelTrevize** [comment]
A dupe of #773, but a better implementation idea than that?

**Comment by kwazulueve** [comment]
Please include also the name of the fleet people are in, in case it is not possible to request the fleet details directly

**Comment by DaneelTrevize** [comment]
A fleet doesn't always have a name, it does always have a boss.  
If you have a boss's CharacterID, you can name the fleet "*CharacterName*'s fleet".

This FR's better able to handle when you know of a CharacterID in a fleet, but don't yet know the fleetID.  
#773 is better able to handle when you knew a fleetID but are no longer sure of any member of it, but it would be a mechanism by which intel would leak out for a fleet you can otherwise no longer access any info for in-game.

**Comment by Flupster** [comment]
This is why I asked for my interpretation of the feature, only showing fleet_id boss doesn't leak everything.

in #773 if you get a spy in fleet, you can have the entire fleets location immediately, their fleet composition, etc etc, mine is barebone, here's a fleet_id's boss, if you have access to the fleet info go get it yourself.

Keep in mind I created this issue within a few minutes of the other issue, it was just fluke coincidence we both were after the same thing at the same time

**Comment by DaneelTrevize** [comment]
Some new fleet-finder endpoint or unauthenticated variation of `GET /fleets/{fleet_id}/` might be nice in an ideal world, but I'm strongly suspecting the simplest and most immediately & hugely beneficial implementation would be as per the detailed OP proposal, of exposing a fleet_boss_character_id and for tools to iterate over the last known fleet members' IDs that are characters for which said tools also hold read_fleet scoped refresh tokens for.

It's not at all likely that these other would-be-FCs dropped fleet at the same time as the last boss, so it should take very few erroring attempts to find a trusting & current fleet member, and then the correct boss character ID via this RF, and thus new details & token to use to resume service with.

**Comment by warlof** [comment]
Yes, please, so we can avoid useless bounced request to fleet endpoint because character is not the boss 😍

**Comment by Flupster** [comment]
Can we get some info from CCP if this is possible or even being looked at, as it stands I have to check through a list of 20 people to see which one is the boss, I just want to know who the boss of the fleet is so I don't have to guess and get 400 errors

**Comment by tsuthers-ccpgames** [comment]
This basically makes sense. I don't know if it's possible yet since I haven't looked at the code but I don't expect it to be hard (I've been surprised before though, no promises).

I've had a quick discussion with a few people re the passive spying fleet boss concern. The short version is:
a) GD doesn't think it's a huge deal for people to know who the fleet boss is, particularly since fleet boss is not necessarily FC.
b) I think that spies could do a lot more damage by just giving access to their location endpoint, knowing where a fleet is seems higher criticality than knowing who the boss is.
c) In general I don't consider it to be the API's job to create trust out of nowhere. I don't intend to let the API become a swiss cheese of side channels, but if you've got spies in your alliance that sounds like something I can't help you with, and I think the increase in usability here is worth the very slight increase in intel a spy could pass on.

so approved I guess?

**Comment by tsuthers-ccpgames** [comment]
This'll deploy Tuesday next week, in a /v2/ of the /characters/{character_id}/fleet endpoint. New version because it's a new required field.

Technically the backend allows fleets without fleet bosses, but I don't think there's any case where this can actually happen barring bugged fleets, pretty sure it's just an artifact of the fleet system being very old. Anyway, it'll be in /dev/ for the usual 6 weeks so give it a good testing and we'll find out if it's not the case I guess.
