### ISSUE TITLE
Character/Corporation/alliance_id endpoints errors

### ISSUE THREAD

**Issue by ImSuperlative** [esi/esi-issues#788]
# Bug
These errors feels pretty random and happens a few times a week. just included a few responses, but these happen to all of the endpoints below.

### Request
`characters/{character_id}/`
`characters/{character_id}/corporationhistory`
`corporations/{corporation_id}/`
`corporations/{corporation_id}/alliancehistory/`
`alliances/{alliance_id}/`

### Response

`ESI Request: alliances/99004514/ returned status code 500`
```
{
  "error": "Invalid 200 response: 'name' is required",
  "response": {
    "date_founded": "2014-06-09T08:59:42Z",
    "creator_id": 1041425275,
    "alliance_id": 99004514,
    "creator_corporation_id": 98124121,
    "ticker": "CArFo",
    "executor_corp_id": 98124121,
    "executor_corporation_id": 98124121
  }
}
```

the corp actually exists.
`ESI Request: corporations/2008116468/ returned status code 404`
```
{
  "error":"Corporation not found"
}
```

same as above, but different error
`ESI Request: corporations/1745740330/alliancehistory/ returned status code 500`
```
{
  "error":"Unhandled internal error encountered!"
}
```

**Comment by ccp-zoetrope** [comment]
`alliances/99004514/` looks like it doesn't have that problem anymore. Looking at the internal error for `corporations/1745740330/alliancehistory/` it looks like it was a one time error that has nothing to do with the actual endpoint itself but had everything to do with the timing of the call. 

`corporations/2008116468/` returning 404 is weird though so that one still needs to be looked into.

**Comment by CarbonAlabel** [comment]
Doesn't seem like any of these are throwing errors anymore, closing.
