### ISSUE TITLE
path get_corporations_corporation_id_industry_jobs requires role "FactoryManager" not granted to director

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#922]
It may be a typo, the "Factory_Manager" role is granted to directors.

The "FactoryManager" is not granted to an account with the director role, thus a character should not be able to this path.
However the server responds if the account has the "Factory_Manager" role.

This path is the only one requiring this role, check https://esi.tech.ccp.is/latest/swagger.json
ctrl F "FactoryManager" only appears at two places, one in the doc, the other in the x-required-role of this path.

**Comment by Aidansavage** [comment]
So... what is incorrect? ESI following game protocol and denying access to someone that does not explicitly have the `Factory Manager` role (which if they're a director, they can just give it to themselves)? Or ESI not following the tooltip description of `Director` and assuming that if a director can do everything a CEO can, they should be able to access ESI information guarded by a required role?

**Comment by guiguilechat** [comment]
what is incorrect is that it requires "FactoryManager" when it should require "Factory_Manager"

**Comment by Aidansavage** [comment]
>what is incorrect is that it requires "FactoryManager" when it should require "Factory_Manager"

It helps to include that from the beginning, given ESI's habit of not having uniform naming schemes. Perhaps a better title would have been "[...] requires invalid role" or some such to avoid people making erroneous assumptions based on a lack of information from others.

**Comment by guiguilechat** [comment]
No. 

The ISSUE here I encountered is that the role required for this path is not present for a character with director.

AFTER THAT I searched and my GUESS is that there is a typo. But this is just my guess, not the bug.

**Comment by lukasni** [comment]
So the issue is a typo in the name of the role, from the looks of it.

It's generally easier to get assistance from people by _not_ calling them names, but you do you. In future please also use the issue templates, as shown in the template text you get when creating an issue through "New Issues":

```# Stop

You're doing it wrong. Go back to the [README.md](https://ccpgames.github.io/esi-issues/) and click on one of the "Opening a new issue" links to start with an appropriate issue template.

Issues submitted without a template are likely to be rejected and closed immediately.```

**Comment by guiguilechat** [comment]
I don't want to get assistance. I'm here to provide a bug report.
I AM the assistance.

**Comment by NathenSample** [comment]
If you don't want to converse with someone over the issue, then don't, and simply await a CCP reply, whilst the main purpose of this repository is for the reporting of issues, it is also for the discussion of them, and some back and forth is to be expected.

The fact you don't want to discuss the issue with a user, does not justify you acting a jackass.

> If the bug is not explained correctly I can try to reformulate

As @lukasni explained, your report does not follow the issue format; If you want "someone to classify this in ESI-bug and correct it on future release" then reporting the issue you want fixing, in the correct format, is probably a better way to go about it rather than attacking people attempting to contribute to the back and forth surrounding an issue.

Your attitude and approach to this issue is obnoxious at best and destructive at worse.

**Comment by Kyria** [comment]
Also, this is not a bug, it's just a typo. 
The least you could do is to follow templates, that everyone (but you) is able to follow. 

As for that report, in case someone wonders about it:
* Director role gives all role, included `Factory_Manager` (just tested it, that's the case)
* `/corporations/{corporation_id}/industry/jobs/` even if it states `FactoryManager` works with someone with director role

So yes, it's just a typo, at least for this endpoint.

**Comment by guiguilechat** [comment]
still not fixed.

**Comment by Aidansavage** [comment]
Considering this issue isn't thumbed up by anyone, is not surprising they haven't given it any attention. Next time, consider bumping it by asking "any progress on this yet?" It's not as rude.

**Comment by guiguilechat** [comment]
I know there is no progress because there's been a new release of esi and the bug is not fixed.

**Comment by a-tal** [comment]
a new release of ESI doesn't mean all random and unrelated endpoints will be resolved. in fact, it almost always means nothing for the endpoints themselves. it might have an impact on some global behaviors or some other aspect of the framework or documentation, but yeah...

this issue is/was a trainwreck. please use the issue templates next time
