### ISSUE TITLE
characters/{character_id}/assets/ returns is_blueprint_copy

### ISSUE THREAD

**Issue by SomePlayer** [esi/esi-issues#952]
# Extra field is_blueprint_copy returned 

The documentation does not say that is_blueprint_copy will be returned. And it is only there if it is a blueprint copy. 

## Routes

- `GET /v1/characters/{character_id}/assets/ `

## Resolution
Update documentation. Or remove is_blueprint_copy from returned results.

# Checklist

Check all boxes that apply to this issue:

- [ x] Inconsistency description is provided
- [ x] Inconsistent route(s) are provided
- [ ] Resolution [will require a version bump](https://esi.github.io/esi-issues/breaking_changes)
- [x ] Resolution [does not require a version bump](https://esi.github.io/esi-issues/breaking_changes)

**Comment by itshouldntdothis** [comment]
Given the posted url version is no longer served by ESI I would suspect that your client was generated based on the latest spec (which includes no spec guarantees in regards to changes over time) rather than using a [version spec](https://developers.eveonline.com/blog/article/esi-quick-reference-for-new-developers-1).

The response described appears to be inline with the [documentation for v3](https://esi.github.io/esi-issues/breaking_changes) of this routes that would be served when using the latest tag.

Assuming that you had previously been using v3 without issue the inclusion of new attributes within the response does not meet the standard of a [breaking change](https://esi.github.io/esi-issues/breaking_changes).
