### ISSUE TITLE
[Improvement] Change status 404 to 200 if no route found /route/{x}/{y}/

### ISSUE THREAD

**Issue by exodus4d** [esi/esi-issues#957]
# Feature Request

I suggest to change the `http 404` status response to `http 200` in case **there is no route found**.

**Why?** 
 If there is no route found this is still a valid response and not a "Client Error" [HTTP 404](https://en.wikipedia.org/wiki/HTTP_404). I would expect a 200 response with an **empty array**.

## Use case

If a user is in a "_wormhole_ systems"/"_abyss_ system" a route will never be found, because there are no stargate connections.  (... custom connections are not send with the request)
 I don´t want to get a 404 for all requests where source or destination system has no stargate connections.

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by cvweiss** [comment]
Can you determine their location first, and then determine if you should be calling a route endpoint?

**Comment by GoldenGnu** [comment]
Both wormhole and abyssal systems  have a fixed id range that is should be easy to check before you send off the requests.
You can find the id ranges in the following link:
https://gist.github.com/a-tal/5ff5199fdbeb745b77cb633b7f4400bb
This comment is just meant to provide a workaround and I neither agree or disagree with this feature request...

**Comment by a-tal** [comment]
no. if you get a 404 - route not found, you have an invalid request. if you're trying to route to/from systems with no stargates, you have to be sure to include the appropriate connections. if this returned a 200, how would you ever know your requests are malformed?

**Comment by guiguilechat** [comment]
The matter is that 404 means there is an issue with the program performing the request.

However, since two wh IDs are correct, the resource route/wh1/wh2 is also correct.
One cannot guess, from the esi doc and the other paths accessible only, if the failure 404 is from an error in the url (eg routes/ instead of route/ ) or from a bad selection of ids.

A better solution would be to return 204 No Content, along with empty array (like the 200).

**Comment by Aidansavage** [comment]
Perhaps read the swagger spec? 
```
          "404": {
            "description": "No route found",
            "examples": {
              "application/json": {
                "error": "Not found message"
              }
             },
```
That clearly defines that if you get a 404 on this endpoint, it's because you told it to do the impossible. And right above that, it tells you what you'd get if you pass a bad request-
```
          "400": {
            "description": "Bad request",
            "examples": {
              "application/json": {
                "error": "Bad request message"
              }
            },
            "schema": {
              "$ref": "#/definitions/bad_request"
            }
          },
```
A "bad selection of ids" as mentioned, isnt the problem of ESI, that is a failure of the program to properly check whether or not they're valid IDs in regards to route generation.

Additionally, based on the use-case, should probably be using the location scope in addition so you arent making 'bad' calls.

**Comment by guiguilechat** [comment]
@ddavaham 
But the resource is found. The resource is well understood by the server, it can be cached.

The issue with 404 is that it counts into the error rate for the app, it needs specific code modification to be handled correctly , the library using it can't be debugged without looking into the spec, and frankly saying "I don't understand your request" when actually it meant "The request has empty solution set" is error -prone to remain correct.

**Comment by cvweiss** [comment]
Just a friendly reminder in case everyone missed it, this issue has been denied and closed.
