### ISSUE TITLE
Corp Roles for NPC corporation returns 403 'Character not in corporation'

### ISSUE THREAD

**Issue by Zifrian** [esi/esi-issues#979]
# Bug

/corporations/{corporation_id}/roles/

Calling this path with an NPC corporation and a character in that corporation returns the message "Forbidden: Character not in corporation" with an error of 403. 

Additionally, I've tried a player character in a player corporation with no personnel manager role and it returns "Character cannot grant roles.", which is consistent with documentation.

## Request

Request that there is a consistent message returned for all corporations, to include NPC corporations when executing this call, such as "Character cannot grant roles or is not a personnel manager."

**Comment by Aidansavage** [comment]
This isn't quite a bug imo. Mainly due to the fact of how bpc corps work in game, as when you leave a player corp, you're suddenly in an npc corp. not to mention players, to the best of my knowledge, _CANNOT_ get any roles beyond the basic default role. Hence. 403 makes sense. 

A more reasonable self-solution is to not parse for corporation information you can get only from player corps in that token is found to be in an npc corp.

**Comment by antihax** [comment]
https://gist.github.com/a-tal/5ff5199fdbeb745b77cb633b7f4400bb

`If corpID > 2,000,000 { do the thing }`
