### ISSUE TITLE
Search ignores quotes even in strict mode and returns multiple results

### ISSUE THREAD

**Issue by jowrjowr** [esi/esi-issues#999]
# Bug

the search endpoint ignores certain non-alphanumeric characters even under strict mode.

strict mode should not return multiple things.

## Request

```
curl -i --compressed -X GET --header 'Accept: application/json' --header 'Accept-Language: en-us'
'https://esi.evetech.net/latest/search/?categity&language=en-us&search=zero&strict=true'


{"character":[95190095,1091292421]}
```

this returns both "zero" and "ze'ro"

for those who are unclear, "zero" and "ze'ro" are not the same thing.

i understand that the dash and quote are explicitly ignored during general queries, but them not being ignored under strict=true would be nice.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

assigning to bartender because nobody else can handle the elasticsearch cluster's magic

**Comment by Aidansavage** [comment]
Iirc this is a known issue re: elastisearch/sphinx that's behind the search endpoint.

**Comment by tsuthers-ccpgames** [comment]
This is working as intended. There are two reasons for this: 
1. The in game search is for humans, not robots. We want it to be as generous as possible with the kinds of mistakes humans make with keyboards
2. Elasticsearch escaping is unsatisfactory

Humans are really bad at remembering that excavator mining drones are actually 'excavator' mining drones, so if you insist on the single quote at the start of the word people can't find what they are after, which is bad because the search is meant to help people find stuff. Stripping the single quotes out functionally makes them optional for human purposes. During the upgrade to elastic search we removed the requirement to get the placement of the hyphen in nullsec system exactly right as well. About 10,000 queries a day were being returned with no results because people were putting the hyphen in the wrong place during a solar system search.

On top of all that, < and > [cannot be escaped at all for some queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html), and during development of the new search system it was observed other syntax escaping behaves inconsistently depending on the type of query and had to be escaped to different levels on a per query basis 😿. We chose to strip significant syntax instead because it's a much more robust solution in the face of inconsistent query handling and preserving the significance of the syntax actually has negative value for humans using the search in most cases.

>strict mode should not return multiple things.

That's never been true. Consider the following: 

https://evewho.com/corp/Neutron+Blaster+Cannon+II
https://evewho.com/pilot/Tristan

Strict mode is maybe a misnomer, it would have been better named "full phrase search". It cares about the order of the words as a whole, instead of tokenizing the query by whitespace and adding a wildcard to the end of each token. However, the query string will still be sanitized the same way all other query strings are.
